# connection: &connection
#   adapter: postgresql
#   host: localhost
#   pool: 5
#   timeout: 5000
#   min_messages: warning
#   username: postgres
#   password: postgres

# development:
#   <<: *connection
#   database: prospects

# test: &test
#   <<: *connection
#   database: prospects_test

# cucumber:
#   <<: *test

development:

  adapter:  mysql2
  encoding:  utf8
  reconnect: false
  database:  phonesale
  username: root
  password: 'root'

test:

  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: phonesale_test
  username: root
  password: 'root'

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ereader_production
  pool: 5
  username: root
  password: root